-- MySQL Script generated by MySQL Workbench
-- Tue Jan 28 10:22:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Aula7
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Aula7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Aula7` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Aula7` ;

-- -----------------------------------------------------
-- Table `Aula7`.`tipocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aula7`.`tipocliente` (
  `i_tipocliente_tipocliente` INT NOT NULL,
  `s_dsctipocliente_tipocliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`i_tipocliente_tipocliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aula7`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aula7`.`cliente` (
  `i_cliente_cliente` INT NOT NULL AUTO_INCREMENT,
  `s_nome_cliente` VARCHAR(50) NOT NULL,
  `s_cpf_cliente` VARCHAR(11) NOT NULL,
  `d_nasc_cliente` DATETIME NULL DEFAULT NULL,
  `i_tipo_cliente` INT NULL,
  PRIMARY KEY (`i_cliente_cliente`),
  INDEX `fk_cliente_tipocliente_idx` (`i_tipo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_tipocliente`
    FOREIGN KEY (`i_tipo_cliente`)
    REFERENCES `Aula7`.`tipocliente` (`i_tipocliente_tipocliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
